module.exports = {
  apps: [{
    name:        'captive-api',
    script:      './backend/src/index.js',
    cwd:         '/home/admin/apps/captive-portal',
    instances:   1,
    exec_mode:   'fork',
    autorestart: true,
    watch:       false,
    max_memory_restart: '256M',
    env: {
      NODE_ENV:         'production',
      PORT:             3000,
      DB_PATH:          '/home/admin/apps/captive-portal/data/captive.db',
      MEDIA_DIR:        '/home/admin/apps/captive-portal/media',
      CORS_ORIGINS: 'http://captive.lan,http://192.168.182.1',
      LAN_IFACE:        'eth1',
      CHILLI_QUERY_CMD: 'sudo chilli_query -s /var/run/chilli.eth1.sock',
    },
    error_file:      '/home/admin/apps/captive-portal/logs/error.log',
    out_file:        '/home/admin/apps/captive-portal/logs/out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    merge_logs:      true,
  }],
};